"""caching of avatar hashes

Revision ID: 1d8984f9f8a4
Revises: 58cc659d1aa6
Create Date: 2016-04-01 19:40:45.072294

"""

# revision identifiers, used by Alembic.
revision = '1d8984f9f8a4'
down_revision = '58cc659d1aa6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
