"""mod post for rich text

Revision ID: bff9d5e27ed4
Revises: afbd16479be7
Create Date: 2016-04-04 15:53:48.548287

"""

# revision identifiers, used by Alembic.
revision = 'bff9d5e27ed4'
down_revision = 'afbd16479be7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
